### ISSUE TITLE
NullReferenceException in Unity 2022.3.0 LTS

### ISSUE THREAD

**Issue by MeisterDerMagie** [keenanwoodall/ExtendedTransformEditor#5]
In the newest LTS release of Unity there is the following error occuring:

`NullReferenceException: Object reference not set to an instance of an object
Beans.Unity.ETE.TransformRotationGUI.get_eulerAngles () (at Assets/_Wichtel/Scripts/Editor/ExtendedTransformEditor/Editor/Utility/TransformRotationGUI.cs:21)
Beans.Unity.ETE.ExtendedTransformEditor.OnInspectorGUI () (at Assets/_Wichtel/Scripts/Editor/ExtendedTransformEditor/Editor/ExtendedTransformEditor.cs:95)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <4911eca47f294e18a7b3306f02701303>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

**Comment by keenanwoodall** [comment]
Fixed in [5a04252](https://github.com/keenanwoodall/ExtendedTransformEditor/commit/5a042525ccb29ac7a9356a7e7d5ee439ed14195b)
